'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="POS_DB")>  _
Partial Public Class POS_DBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Inserttbl_user(instance As tbl_user)
    End Sub
  Partial Private Sub Updatetbl_user(instance As tbl_user)
    End Sub
  Partial Private Sub Deletetbl_user(instance As tbl_user)
    End Sub
  Partial Private Sub Inserttbl_medicine_inventory(instance As tbl_medicine_inventory)
    End Sub
  Partial Private Sub Updatetbl_medicine_inventory(instance As tbl_medicine_inventory)
    End Sub
  Partial Private Sub Deletetbl_medicine_inventory(instance As tbl_medicine_inventory)
    End Sub
  Partial Private Sub Inserttbl_account_log(instance As tbl_account_log)
    End Sub
  Partial Private Sub Updatetbl_account_log(instance As tbl_account_log)
    End Sub
  Partial Private Sub Deletetbl_account_log(instance As tbl_account_log)
    End Sub
  Partial Private Sub Inserttbl_product(instance As tbl_product)
    End Sub
  Partial Private Sub Updatetbl_product(instance As tbl_product)
    End Sub
  Partial Private Sub Deletetbl_product(instance As tbl_product)
    End Sub
  Partial Private Sub Inserttbl_medicine_type(instance As tbl_medicine_type)
    End Sub
  Partial Private Sub Updatetbl_medicine_type(instance As tbl_medicine_type)
    End Sub
  Partial Private Sub Deletetbl_medicine_type(instance As tbl_medicine_type)
    End Sub
  Partial Private Sub Inserttbl_unit_type(instance As tbl_unit_type)
    End Sub
  Partial Private Sub Updatetbl_unit_type(instance As tbl_unit_type)
    End Sub
  Partial Private Sub Deletetbl_unit_type(instance As tbl_unit_type)
    End Sub
  Partial Private Sub Inserttbl_POSTransaction(instance As tbl_POSTransaction)
    End Sub
  Partial Private Sub Updatetbl_POSTransaction(instance As tbl_POSTransaction)
    End Sub
  Partial Private Sub Deletetbl_POSTransaction(instance As tbl_POSTransaction)
    End Sub
  Partial Private Sub Inserttbl_POSTransactionDetail(instance As tbl_POSTransactionDetail)
    End Sub
  Partial Private Sub Updatetbl_POSTransactionDetail(instance As tbl_POSTransactionDetail)
    End Sub
  Partial Private Sub Deletetbl_POSTransactionDetail(instance As tbl_POSTransactionDetail)
    End Sub
  Partial Private Sub Inserttbl_Notification(instance As tbl_Notification)
    End Sub
  Partial Private Sub Updatetbl_Notification(instance As tbl_Notification)
    End Sub
  Partial Private Sub Deletetbl_Notification(instance As tbl_Notification)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.POS_System.My.MySettings.Default.POS_DBConnectionString3, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tbl_users() As System.Data.Linq.Table(Of tbl_user)
		Get
			Return Me.GetTable(Of tbl_user)
		End Get
	End Property
	
	Public ReadOnly Property tbl_medicine_inventories() As System.Data.Linq.Table(Of tbl_medicine_inventory)
		Get
			Return Me.GetTable(Of tbl_medicine_inventory)
		End Get
	End Property
	
	Public ReadOnly Property tbl_account_logs() As System.Data.Linq.Table(Of tbl_account_log)
		Get
			Return Me.GetTable(Of tbl_account_log)
		End Get
	End Property
	
	Public ReadOnly Property tbl_products() As System.Data.Linq.Table(Of tbl_product)
		Get
			Return Me.GetTable(Of tbl_product)
		End Get
	End Property
	
	Public ReadOnly Property tbl_medicine_types() As System.Data.Linq.Table(Of tbl_medicine_type)
		Get
			Return Me.GetTable(Of tbl_medicine_type)
		End Get
	End Property
	
	Public ReadOnly Property tbl_unit_types() As System.Data.Linq.Table(Of tbl_unit_type)
		Get
			Return Me.GetTable(Of tbl_unit_type)
		End Get
	End Property
	
	Public ReadOnly Property tbl_POSTransactions() As System.Data.Linq.Table(Of tbl_POSTransaction)
		Get
			Return Me.GetTable(Of tbl_POSTransaction)
		End Get
	End Property
	
	Public ReadOnly Property tbl_POSTransactionDetails() As System.Data.Linq.Table(Of tbl_POSTransactionDetail)
		Get
			Return Me.GetTable(Of tbl_POSTransactionDetail)
		End Get
	End Property
	
	Public ReadOnly Property tbl_Notifications() As System.Data.Linq.Table(Of tbl_Notification)
		Get
			Return Me.GetTable(Of tbl_Notification)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_InsertPOSTransaction")>  _
	Public Function SP_InsertPOSTransaction(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CustomerName", DbType:="VarChar(255)")> ByVal customerName As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TotalItems", DbType:="Int")> ByVal totalItems As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VatSales", DbType:="Decimal(18,2)")> ByVal vatSales As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VatExemptSales", DbType:="Decimal(18,2)")> ByVal vatExemptSales As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TotalSales", DbType:="Decimal(18,2)")> ByVal totalSales As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VatAmount", DbType:="Decimal(18,2)")> ByVal vatAmount As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TotalAmount", DbType:="Decimal(18,2)")> ByVal totalAmount As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PaymentMethod", DbType:="VarChar(50)")> ByVal paymentMethod As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CashReceived", DbType:="Decimal(18,2)")> ByVal cashReceived As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ChangeAmount", DbType:="Decimal(18,2)")> ByVal changeAmount As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CreatedBy", DbType:="VarChar(20)")> ByVal createdBy As String) As ISingleResult(Of SP_InsertPOSTransactionResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), customerName, totalItems, vatSales, vatExemptSales, totalSales, vatAmount, totalAmount, paymentMethod, cashReceived, changeAmount, createdBy)
		Return CType(result.ReturnValue,ISingleResult(Of SP_InsertPOSTransactionResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SP_InsertPOSTransactionDetails")>  _
	Public Function SP_InsertPOSTransactionDetails(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TransactionID", DbType:="Int")> ByVal transactionID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ProductID", DbType:="VarChar(255)")> ByVal productID As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ProductName", DbType:="VarChar(255)")> ByVal productName As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Price", DbType:="Decimal(18,2)")> ByVal price As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Quantity", DbType:="Int")> ByVal quantity As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ExtendPrice", DbType:="Decimal(18,2)")> ByVal extendPrice As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Discount", DbType:="Decimal(18,2)")> ByVal discount As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Total", DbType:="Decimal(18,2)")> ByVal total As System.Nullable(Of Decimal)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), transactionID, productID, productName, price, quantity, extendPrice, discount, total)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_user")>  _
Partial Public Class tbl_user
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _user_id As Integer
	
	Private _username As String
	
	Private _password As String
	
	Private _fullname As String
	
	Private _contact As String
	
	Private _account_type As String
	
	Private _account_status As String
	
	Private _image As System.Data.Linq.Binary
	
	Private _last_login As System.Nullable(Of Date)
	
	Private _date_created As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onuser_idChanging(value As Integer)
    End Sub
    Partial Private Sub Onuser_idChanged()
    End Sub
    Partial Private Sub OnusernameChanging(value As String)
    End Sub
    Partial Private Sub OnusernameChanged()
    End Sub
    Partial Private Sub OnpasswordChanging(value As String)
    End Sub
    Partial Private Sub OnpasswordChanged()
    End Sub
    Partial Private Sub OnfullnameChanging(value As String)
    End Sub
    Partial Private Sub OnfullnameChanged()
    End Sub
    Partial Private Sub OncontactChanging(value As String)
    End Sub
    Partial Private Sub OncontactChanged()
    End Sub
    Partial Private Sub Onaccount_typeChanging(value As String)
    End Sub
    Partial Private Sub Onaccount_typeChanged()
    End Sub
    Partial Private Sub Onaccount_statusChanging(value As String)
    End Sub
    Partial Private Sub Onaccount_statusChanged()
    End Sub
    Partial Private Sub OnimageChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnimageChanged()
    End Sub
    Partial Private Sub Onlast_loginChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onlast_loginChanged()
    End Sub
    Partial Private Sub Ondate_createdChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Ondate_createdChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property user_id() As Integer
		Get
			Return Me._user_id
		End Get
		Set
			If ((Me._user_id = value)  _
						= false) Then
				Me.Onuser_idChanging(value)
				Me.SendPropertyChanging
				Me._user_id = value
				Me.SendPropertyChanged("user_id")
				Me.Onuser_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_username", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property username() As String
		Get
			Return Me._username
		End Get
		Set
			If (String.Equals(Me._username, value) = false) Then
				Me.OnusernameChanging(value)
				Me.SendPropertyChanging
				Me._username = value
				Me.SendPropertyChanged("username")
				Me.OnusernameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_password", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property password() As String
		Get
			Return Me._password
		End Get
		Set
			If (String.Equals(Me._password, value) = false) Then
				Me.OnpasswordChanging(value)
				Me.SendPropertyChanging
				Me._password = value
				Me.SendPropertyChanged("password")
				Me.OnpasswordChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fullname", DbType:="VarChar(50)")>  _
	Public Property fullname() As String
		Get
			Return Me._fullname
		End Get
		Set
			If (String.Equals(Me._fullname, value) = false) Then
				Me.OnfullnameChanging(value)
				Me.SendPropertyChanging
				Me._fullname = value
				Me.SendPropertyChanged("fullname")
				Me.OnfullnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_contact", DbType:="VarChar(15)")>  _
	Public Property contact() As String
		Get
			Return Me._contact
		End Get
		Set
			If (String.Equals(Me._contact, value) = false) Then
				Me.OncontactChanging(value)
				Me.SendPropertyChanging
				Me._contact = value
				Me.SendPropertyChanged("contact")
				Me.OncontactChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_account_type", DbType:="VarChar(15)")>  _
	Public Property account_type() As String
		Get
			Return Me._account_type
		End Get
		Set
			If (String.Equals(Me._account_type, value) = false) Then
				Me.Onaccount_typeChanging(value)
				Me.SendPropertyChanging
				Me._account_type = value
				Me.SendPropertyChanged("account_type")
				Me.Onaccount_typeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_account_status", DbType:="VarChar(15)")>  _
	Public Property account_status() As String
		Get
			Return Me._account_status
		End Get
		Set
			If (String.Equals(Me._account_status, value) = false) Then
				Me.Onaccount_statusChanging(value)
				Me.SendPropertyChanging
				Me._account_status = value
				Me.SendPropertyChanged("account_status")
				Me.Onaccount_statusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_image", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property image() As System.Data.Linq.Binary
		Get
			Return Me._image
		End Get
		Set
			If (Object.Equals(Me._image, value) = false) Then
				Me.OnimageChanging(value)
				Me.SendPropertyChanging
				Me._image = value
				Me.SendPropertyChanged("image")
				Me.OnimageChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_last_login", DbType:="DateTime")>  _
	Public Property last_login() As System.Nullable(Of Date)
		Get
			Return Me._last_login
		End Get
		Set
			If (Me._last_login.Equals(value) = false) Then
				Me.Onlast_loginChanging(value)
				Me.SendPropertyChanging
				Me._last_login = value
				Me.SendPropertyChanged("last_login")
				Me.Onlast_loginChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_date_created", DbType:="DateTime")>  _
	Public Property date_created() As System.Nullable(Of Date)
		Get
			Return Me._date_created
		End Get
		Set
			If (Me._date_created.Equals(value) = false) Then
				Me.Ondate_createdChanging(value)
				Me.SendPropertyChanging
				Me._date_created = value
				Me.SendPropertyChanged("date_created")
				Me.Ondate_createdChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_medicine_inventory")>  _
Partial Public Class tbl_medicine_inventory
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _medicine_id As Integer
	
	Private _medicine_code As String
	
	Private _medicine_name As String
	
	Private _brand As String
	
	Private _medicine_type As String
	
	Private _unit As String
	
	Private _quantity As System.Nullable(Of Integer)
	
	Private _reorder_level As System.Nullable(Of Integer)
	
	Private _expiry_date As System.Nullable(Of Date)
	
	Private _price As System.Nullable(Of Decimal)
	
	Private _supplier_id As String
	
	Private _date_added As System.Nullable(Of Date)
	
	Private _is_archived As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onmedicine_idChanging(value As Integer)
    End Sub
    Partial Private Sub Onmedicine_idChanged()
    End Sub
    Partial Private Sub Onmedicine_codeChanging(value As String)
    End Sub
    Partial Private Sub Onmedicine_codeChanged()
    End Sub
    Partial Private Sub Onmedicine_nameChanging(value As String)
    End Sub
    Partial Private Sub Onmedicine_nameChanged()
    End Sub
    Partial Private Sub OnbrandChanging(value As String)
    End Sub
    Partial Private Sub OnbrandChanged()
    End Sub
    Partial Private Sub Onmedicine_typeChanging(value As String)
    End Sub
    Partial Private Sub Onmedicine_typeChanged()
    End Sub
    Partial Private Sub OnunitChanging(value As String)
    End Sub
    Partial Private Sub OnunitChanged()
    End Sub
    Partial Private Sub OnquantityChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnquantityChanged()
    End Sub
    Partial Private Sub Onreorder_levelChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onreorder_levelChanged()
    End Sub
    Partial Private Sub Onexpiry_dateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onexpiry_dateChanged()
    End Sub
    Partial Private Sub OnpriceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnpriceChanged()
    End Sub
    Partial Private Sub Onsupplier_idChanging(value As String)
    End Sub
    Partial Private Sub Onsupplier_idChanged()
    End Sub
    Partial Private Sub Ondate_addedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Ondate_addedChanged()
    End Sub
    Partial Private Sub Onis_archivedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onis_archivedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_medicine_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property medicine_id() As Integer
		Get
			Return Me._medicine_id
		End Get
		Set
			If ((Me._medicine_id = value)  _
						= false) Then
				Me.Onmedicine_idChanging(value)
				Me.SendPropertyChanging
				Me._medicine_id = value
				Me.SendPropertyChanged("medicine_id")
				Me.Onmedicine_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_medicine_code", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property medicine_code() As String
		Get
			Return Me._medicine_code
		End Get
		Set
			If (String.Equals(Me._medicine_code, value) = false) Then
				Me.Onmedicine_codeChanging(value)
				Me.SendPropertyChanging
				Me._medicine_code = value
				Me.SendPropertyChanged("medicine_code")
				Me.Onmedicine_codeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_medicine_name", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property medicine_name() As String
		Get
			Return Me._medicine_name
		End Get
		Set
			If (String.Equals(Me._medicine_name, value) = false) Then
				Me.Onmedicine_nameChanging(value)
				Me.SendPropertyChanging
				Me._medicine_name = value
				Me.SendPropertyChanged("medicine_name")
				Me.Onmedicine_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_brand", DbType:="VarChar(100)")>  _
	Public Property brand() As String
		Get
			Return Me._brand
		End Get
		Set
			If (String.Equals(Me._brand, value) = false) Then
				Me.OnbrandChanging(value)
				Me.SendPropertyChanging
				Me._brand = value
				Me.SendPropertyChanged("brand")
				Me.OnbrandChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_medicine_type", DbType:="VarChar(50)")>  _
	Public Property medicine_type() As String
		Get
			Return Me._medicine_type
		End Get
		Set
			If (String.Equals(Me._medicine_type, value) = false) Then
				Me.Onmedicine_typeChanging(value)
				Me.SendPropertyChanging
				Me._medicine_type = value
				Me.SendPropertyChanged("medicine_type")
				Me.Onmedicine_typeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_unit", DbType:="VarChar(20)")>  _
	Public Property unit() As String
		Get
			Return Me._unit
		End Get
		Set
			If (String.Equals(Me._unit, value) = false) Then
				Me.OnunitChanging(value)
				Me.SendPropertyChanging
				Me._unit = value
				Me.SendPropertyChanged("unit")
				Me.OnunitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_quantity", DbType:="Int")>  _
	Public Property quantity() As System.Nullable(Of Integer)
		Get
			Return Me._quantity
		End Get
		Set
			If (Me._quantity.Equals(value) = false) Then
				Me.OnquantityChanging(value)
				Me.SendPropertyChanging
				Me._quantity = value
				Me.SendPropertyChanged("quantity")
				Me.OnquantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reorder_level", DbType:="Int")>  _
	Public Property reorder_level() As System.Nullable(Of Integer)
		Get
			Return Me._reorder_level
		End Get
		Set
			If (Me._reorder_level.Equals(value) = false) Then
				Me.Onreorder_levelChanging(value)
				Me.SendPropertyChanging
				Me._reorder_level = value
				Me.SendPropertyChanged("reorder_level")
				Me.Onreorder_levelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expiry_date", DbType:="Date")>  _
	Public Property expiry_date() As System.Nullable(Of Date)
		Get
			Return Me._expiry_date
		End Get
		Set
			If (Me._expiry_date.Equals(value) = false) Then
				Me.Onexpiry_dateChanging(value)
				Me.SendPropertyChanging
				Me._expiry_date = value
				Me.SendPropertyChanged("expiry_date")
				Me.Onexpiry_dateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_price", DbType:="Decimal(10,2)")>  _
	Public Property price() As System.Nullable(Of Decimal)
		Get
			Return Me._price
		End Get
		Set
			If (Me._price.Equals(value) = false) Then
				Me.OnpriceChanging(value)
				Me.SendPropertyChanging
				Me._price = value
				Me.SendPropertyChanged("price")
				Me.OnpriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_supplier_id", DbType:="VarChar(50)")>  _
	Public Property supplier_id() As String
		Get
			Return Me._supplier_id
		End Get
		Set
			If (String.Equals(Me._supplier_id, value) = false) Then
				Me.Onsupplier_idChanging(value)
				Me.SendPropertyChanging
				Me._supplier_id = value
				Me.SendPropertyChanged("supplier_id")
				Me.Onsupplier_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_date_added", DbType:="DateTime")>  _
	Public Property date_added() As System.Nullable(Of Date)
		Get
			Return Me._date_added
		End Get
		Set
			If (Me._date_added.Equals(value) = false) Then
				Me.Ondate_addedChanging(value)
				Me.SendPropertyChanging
				Me._date_added = value
				Me.SendPropertyChanged("date_added")
				Me.Ondate_addedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_is_archived", DbType:="Bit")>  _
	Public Property is_archived() As System.Nullable(Of Boolean)
		Get
			Return Me._is_archived
		End Get
		Set
			If (Me._is_archived.Equals(value) = false) Then
				Me.Onis_archivedChanging(value)
				Me.SendPropertyChanging
				Me._is_archived = value
				Me.SendPropertyChanged("is_archived")
				Me.Onis_archivedChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_account_log")>  _
Partial Public Class tbl_account_log
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _id As Integer
	
	Private _user_id As String
	
	Private _date As System.Nullable(Of Date)
	
	Private _time As String
	
	Private _history_log As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidChanging(value As Integer)
    End Sub
    Partial Private Sub OnidChanged()
    End Sub
    Partial Private Sub Onuser_idChanging(value As String)
    End Sub
    Partial Private Sub Onuser_idChanged()
    End Sub
    Partial Private Sub OndateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndateChanged()
    End Sub
    Partial Private Sub OntimeChanging(value As String)
    End Sub
    Partial Private Sub OntimeChanged()
    End Sub
    Partial Private Sub Onhistory_logChanging(value As String)
    End Sub
    Partial Private Sub Onhistory_logChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property id() As Integer
		Get
			Return Me._id
		End Get
		Set
			If ((Me._id = value)  _
						= false) Then
				Me.OnidChanging(value)
				Me.SendPropertyChanging
				Me._id = value
				Me.SendPropertyChanged("id")
				Me.OnidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_id", DbType:="VarChar(50)")>  _
	Public Property user_id() As String
		Get
			Return Me._user_id
		End Get
		Set
			If (String.Equals(Me._user_id, value) = false) Then
				Me.Onuser_idChanging(value)
				Me.SendPropertyChanging
				Me._user_id = value
				Me.SendPropertyChanged("user_id")
				Me.Onuser_idChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="date", Storage:="_date", DbType:="Date")>  _
	Public Property [date]() As System.Nullable(Of Date)
		Get
			Return Me._date
		End Get
		Set
			If (Me._date.Equals(value) = false) Then
				Me.OndateChanging(value)
				Me.SendPropertyChanging
				Me._date = value
				Me.SendPropertyChanged("[date]")
				Me.OndateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_time", DbType:="VarChar(50)")>  _
	Public Property time() As String
		Get
			Return Me._time
		End Get
		Set
			If (String.Equals(Me._time, value) = false) Then
				Me.OntimeChanging(value)
				Me.SendPropertyChanging
				Me._time = value
				Me.SendPropertyChanged("time")
				Me.OntimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_history_log", DbType:="VarChar(50)")>  _
	Public Property history_log() As String
		Get
			Return Me._history_log
		End Get
		Set
			If (String.Equals(Me._history_log, value) = false) Then
				Me.Onhistory_logChanging(value)
				Me.SendPropertyChanging
				Me._history_log = value
				Me.SendPropertyChanged("history_log")
				Me.Onhistory_logChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_product")>  _
Partial Public Class tbl_product
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ProductID As Integer
	
	Private _ProductCode As String
	
	Private _GenericName As String
	
	Private _BrandName As String
	
	Private _DrugType As String
	
	Private _Unit As String
	
	Private _UnitValue As String
	
	Private _CostPrice As System.Nullable(Of Double)
	
	Private _ProfitPercent As System.Nullable(Of Double)
	
	Private _SellingPrice As System.Nullable(Of Double)
	
	Private _ExpiryDate As System.Nullable(Of Date)
	
	Private _Insturction As String
	
	Private _Packing As String
	
	Private _Quantity As System.Nullable(Of Double)
	
	Private _dateAdded As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnProductIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnProductIDChanged()
    End Sub
    Partial Private Sub OnProductCodeChanging(value As String)
    End Sub
    Partial Private Sub OnProductCodeChanged()
    End Sub
    Partial Private Sub OnGenericNameChanging(value As String)
    End Sub
    Partial Private Sub OnGenericNameChanged()
    End Sub
    Partial Private Sub OnBrandNameChanging(value As String)
    End Sub
    Partial Private Sub OnBrandNameChanged()
    End Sub
    Partial Private Sub OnDrugTypeChanging(value As String)
    End Sub
    Partial Private Sub OnDrugTypeChanged()
    End Sub
    Partial Private Sub OnUnitChanging(value As String)
    End Sub
    Partial Private Sub OnUnitChanged()
    End Sub
    Partial Private Sub OnUnitValueChanging(value As String)
    End Sub
    Partial Private Sub OnUnitValueChanged()
    End Sub
    Partial Private Sub OnCostPriceChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnCostPriceChanged()
    End Sub
    Partial Private Sub OnProfitPercentChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnProfitPercentChanged()
    End Sub
    Partial Private Sub OnSellingPriceChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnSellingPriceChanged()
    End Sub
    Partial Private Sub OnExpiryDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnExpiryDateChanged()
    End Sub
    Partial Private Sub OnInsturctionChanging(value As String)
    End Sub
    Partial Private Sub OnInsturctionChanged()
    End Sub
    Partial Private Sub OnPackingChanging(value As String)
    End Sub
    Partial Private Sub OnPackingChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    Partial Private Sub OndateAddedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndateAddedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ProductID() As Integer
		Get
			Return Me._ProductID
		End Get
		Set
			If ((Me._ProductID = value)  _
						= false) Then
				Me.OnProductIDChanging(value)
				Me.SendPropertyChanging
				Me._ProductID = value
				Me.SendPropertyChanged("ProductID")
				Me.OnProductIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductCode", DbType:="VarChar(50)")>  _
	Public Property ProductCode() As String
		Get
			Return Me._ProductCode
		End Get
		Set
			If (String.Equals(Me._ProductCode, value) = false) Then
				Me.OnProductCodeChanging(value)
				Me.SendPropertyChanging
				Me._ProductCode = value
				Me.SendPropertyChanged("ProductCode")
				Me.OnProductCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GenericName", DbType:="VarChar(50)")>  _
	Public Property GenericName() As String
		Get
			Return Me._GenericName
		End Get
		Set
			If (String.Equals(Me._GenericName, value) = false) Then
				Me.OnGenericNameChanging(value)
				Me.SendPropertyChanging
				Me._GenericName = value
				Me.SendPropertyChanged("GenericName")
				Me.OnGenericNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BrandName", DbType:="VarChar(50)")>  _
	Public Property BrandName() As String
		Get
			Return Me._BrandName
		End Get
		Set
			If (String.Equals(Me._BrandName, value) = false) Then
				Me.OnBrandNameChanging(value)
				Me.SendPropertyChanging
				Me._BrandName = value
				Me.SendPropertyChanged("BrandName")
				Me.OnBrandNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DrugType", DbType:="VarChar(50)")>  _
	Public Property DrugType() As String
		Get
			Return Me._DrugType
		End Get
		Set
			If (String.Equals(Me._DrugType, value) = false) Then
				Me.OnDrugTypeChanging(value)
				Me.SendPropertyChanging
				Me._DrugType = value
				Me.SendPropertyChanged("DrugType")
				Me.OnDrugTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Unit", DbType:="VarChar(50)")>  _
	Public Property Unit() As String
		Get
			Return Me._Unit
		End Get
		Set
			If (String.Equals(Me._Unit, value) = false) Then
				Me.OnUnitChanging(value)
				Me.SendPropertyChanging
				Me._Unit = value
				Me.SendPropertyChanged("Unit")
				Me.OnUnitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnitValue", DbType:="VarChar(50)")>  _
	Public Property UnitValue() As String
		Get
			Return Me._UnitValue
		End Get
		Set
			If (String.Equals(Me._UnitValue, value) = false) Then
				Me.OnUnitValueChanging(value)
				Me.SendPropertyChanging
				Me._UnitValue = value
				Me.SendPropertyChanged("UnitValue")
				Me.OnUnitValueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostPrice", DbType:="Float")>  _
	Public Property CostPrice() As System.Nullable(Of Double)
		Get
			Return Me._CostPrice
		End Get
		Set
			If (Me._CostPrice.Equals(value) = false) Then
				Me.OnCostPriceChanging(value)
				Me.SendPropertyChanging
				Me._CostPrice = value
				Me.SendPropertyChanged("CostPrice")
				Me.OnCostPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProfitPercent", DbType:="Float")>  _
	Public Property ProfitPercent() As System.Nullable(Of Double)
		Get
			Return Me._ProfitPercent
		End Get
		Set
			If (Me._ProfitPercent.Equals(value) = false) Then
				Me.OnProfitPercentChanging(value)
				Me.SendPropertyChanging
				Me._ProfitPercent = value
				Me.SendPropertyChanged("ProfitPercent")
				Me.OnProfitPercentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SellingPrice", DbType:="Float")>  _
	Public Property SellingPrice() As System.Nullable(Of Double)
		Get
			Return Me._SellingPrice
		End Get
		Set
			If (Me._SellingPrice.Equals(value) = false) Then
				Me.OnSellingPriceChanging(value)
				Me.SendPropertyChanging
				Me._SellingPrice = value
				Me.SendPropertyChanged("SellingPrice")
				Me.OnSellingPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExpiryDate", DbType:="Date")>  _
	Public Property ExpiryDate() As System.Nullable(Of Date)
		Get
			Return Me._ExpiryDate
		End Get
		Set
			If (Me._ExpiryDate.Equals(value) = false) Then
				Me.OnExpiryDateChanging(value)
				Me.SendPropertyChanging
				Me._ExpiryDate = value
				Me.SendPropertyChanged("ExpiryDate")
				Me.OnExpiryDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Insturction", DbType:="VarChar(255)")>  _
	Public Property Insturction() As String
		Get
			Return Me._Insturction
		End Get
		Set
			If (String.Equals(Me._Insturction, value) = false) Then
				Me.OnInsturctionChanging(value)
				Me.SendPropertyChanging
				Me._Insturction = value
				Me.SendPropertyChanged("Insturction")
				Me.OnInsturctionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Packing", DbType:="VarChar(50)")>  _
	Public Property Packing() As String
		Get
			Return Me._Packing
		End Get
		Set
			If (String.Equals(Me._Packing, value) = false) Then
				Me.OnPackingChanging(value)
				Me.SendPropertyChanging
				Me._Packing = value
				Me.SendPropertyChanged("Packing")
				Me.OnPackingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="Float")>  _
	Public Property Quantity() As System.Nullable(Of Double)
		Get
			Return Me._Quantity
		End Get
		Set
			If (Me._Quantity.Equals(value) = false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dateAdded", DbType:="Date")>  _
	Public Property dateAdded() As System.Nullable(Of Date)
		Get
			Return Me._dateAdded
		End Get
		Set
			If (Me._dateAdded.Equals(value) = false) Then
				Me.OndateAddedChanging(value)
				Me.SendPropertyChanging
				Me._dateAdded = value
				Me.SendPropertyChanged("dateAdded")
				Me.OndateAddedChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_medicine_types")>  _
Partial Public Class tbl_medicine_type
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _Medicine_Type As String
	
	Private _Status As String
	
	Private _dateCreated As System.Nullable(Of Date)
	
	Private _UpdatedOn As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnMedicine_TypeChanging(value As String)
    End Sub
    Partial Private Sub OnMedicine_TypeChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As String)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OndateCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndateCreatedChanged()
    End Sub
    Partial Private Sub OnUpdatedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdatedOnChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Medicine_Type", DbType:="VarChar(50)")>  _
	Public Property Medicine_Type() As String
		Get
			Return Me._Medicine_Type
		End Get
		Set
			If (String.Equals(Me._Medicine_Type, value) = false) Then
				Me.OnMedicine_TypeChanging(value)
				Me.SendPropertyChanging
				Me._Medicine_Type = value
				Me.SendPropertyChanged("Medicine_Type")
				Me.OnMedicine_TypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(50)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dateCreated", DbType:="DateTime")>  _
	Public Property dateCreated() As System.Nullable(Of Date)
		Get
			Return Me._dateCreated
		End Get
		Set
			If (Me._dateCreated.Equals(value) = false) Then
				Me.OndateCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dateCreated = value
				Me.SendPropertyChanged("dateCreated")
				Me.OndateCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UpdatedOn", DbType:="DateTime")>  _
	Public Property UpdatedOn() As System.Nullable(Of Date)
		Get
			Return Me._UpdatedOn
		End Get
		Set
			If (Me._UpdatedOn.Equals(value) = false) Then
				Me.OnUpdatedOnChanging(value)
				Me.SendPropertyChanging
				Me._UpdatedOn = value
				Me.SendPropertyChanged("UpdatedOn")
				Me.OnUpdatedOnChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_unit_type")>  _
Partial Public Class tbl_unit_type
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _Unit_Name As String
	
	Private _Status As String
	
	Private _dateCreated As System.Nullable(Of Date)
	
	Private _UpdatedOn As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnUnit_NameChanging(value As String)
    End Sub
    Partial Private Sub OnUnit_NameChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As String)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OndateCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndateCreatedChanged()
    End Sub
    Partial Private Sub OnUpdatedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdatedOnChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Unit_Name", DbType:="VarChar(50)")>  _
	Public Property Unit_Name() As String
		Get
			Return Me._Unit_Name
		End Get
		Set
			If (String.Equals(Me._Unit_Name, value) = false) Then
				Me.OnUnit_NameChanging(value)
				Me.SendPropertyChanging
				Me._Unit_Name = value
				Me.SendPropertyChanged("Unit_Name")
				Me.OnUnit_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(50)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dateCreated", DbType:="DateTime")>  _
	Public Property dateCreated() As System.Nullable(Of Date)
		Get
			Return Me._dateCreated
		End Get
		Set
			If (Me._dateCreated.Equals(value) = false) Then
				Me.OndateCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dateCreated = value
				Me.SendPropertyChanged("dateCreated")
				Me.OndateCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UpdatedOn", DbType:="DateTime")>  _
	Public Property UpdatedOn() As System.Nullable(Of Date)
		Get
			Return Me._UpdatedOn
		End Get
		Set
			If (Me._UpdatedOn.Equals(value) = false) Then
				Me.OnUpdatedOnChanging(value)
				Me.SendPropertyChanging
				Me._UpdatedOn = value
				Me.SendPropertyChanged("UpdatedOn")
				Me.OnUpdatedOnChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_POSTransactions")>  _
Partial Public Class tbl_POSTransaction
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _TransactionID As Integer
	
	Private _TransactionDate As Date
	
	Private _CustomerName As String
	
	Private _TotalItems As Integer
	
	Private _VatSales As Decimal
	
	Private _VatExemptSales As Decimal
	
	Private _TotalSales As System.Nullable(Of Decimal)
	
	Private _VatAmount As Decimal
	
	Private _TotalAmount As Decimal
	
	Private _PaymentMethod As String
	
	Private _CashReceived As System.Nullable(Of Decimal)
	
	Private _ChangeAmount As System.Nullable(Of Decimal)
	
	Private _CreatedBy As String
	
	Private _CreatedAt As Date
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnTransactionIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnTransactionIDChanged()
    End Sub
    Partial Private Sub OnTransactionDateChanging(value As Date)
    End Sub
    Partial Private Sub OnTransactionDateChanged()
    End Sub
    Partial Private Sub OnCustomerNameChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerNameChanged()
    End Sub
    Partial Private Sub OnTotalItemsChanging(value As Integer)
    End Sub
    Partial Private Sub OnTotalItemsChanged()
    End Sub
    Partial Private Sub OnVatSalesChanging(value As Decimal)
    End Sub
    Partial Private Sub OnVatSalesChanged()
    End Sub
    Partial Private Sub OnVatExemptSalesChanging(value As Decimal)
    End Sub
    Partial Private Sub OnVatExemptSalesChanged()
    End Sub
    Partial Private Sub OnTotalSalesChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnTotalSalesChanged()
    End Sub
    Partial Private Sub OnVatAmountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnVatAmountChanged()
    End Sub
    Partial Private Sub OnTotalAmountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalAmountChanged()
    End Sub
    Partial Private Sub OnPaymentMethodChanging(value As String)
    End Sub
    Partial Private Sub OnPaymentMethodChanged()
    End Sub
    Partial Private Sub OnCashReceivedChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCashReceivedChanged()
    End Sub
    Partial Private Sub OnChangeAmountChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnChangeAmountChanged()
    End Sub
    Partial Private Sub OnCreatedByChanging(value As String)
    End Sub
    Partial Private Sub OnCreatedByChanged()
    End Sub
    Partial Private Sub OnCreatedAtChanging(value As Date)
    End Sub
    Partial Private Sub OnCreatedAtChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TransactionID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property TransactionID() As Integer
		Get
			Return Me._TransactionID
		End Get
		Set
			If ((Me._TransactionID = value)  _
						= false) Then
				Me.OnTransactionIDChanging(value)
				Me.SendPropertyChanging
				Me._TransactionID = value
				Me.SendPropertyChanged("TransactionID")
				Me.OnTransactionIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TransactionDate", DbType:="DateTime NOT NULL")>  _
	Public Property TransactionDate() As Date
		Get
			Return Me._TransactionDate
		End Get
		Set
			If ((Me._TransactionDate = value)  _
						= false) Then
				Me.OnTransactionDateChanging(value)
				Me.SendPropertyChanging
				Me._TransactionDate = value
				Me.SendPropertyChanged("TransactionDate")
				Me.OnTransactionDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerName", DbType:="NVarChar(150)")>  _
	Public Property CustomerName() As String
		Get
			Return Me._CustomerName
		End Get
		Set
			If (String.Equals(Me._CustomerName, value) = false) Then
				Me.OnCustomerNameChanging(value)
				Me.SendPropertyChanging
				Me._CustomerName = value
				Me.SendPropertyChanged("CustomerName")
				Me.OnCustomerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalItems", DbType:="Int NOT NULL")>  _
	Public Property TotalItems() As Integer
		Get
			Return Me._TotalItems
		End Get
		Set
			If ((Me._TotalItems = value)  _
						= false) Then
				Me.OnTotalItemsChanging(value)
				Me.SendPropertyChanging
				Me._TotalItems = value
				Me.SendPropertyChanged("TotalItems")
				Me.OnTotalItemsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VatSales", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property VatSales() As Decimal
		Get
			Return Me._VatSales
		End Get
		Set
			If ((Me._VatSales = value)  _
						= false) Then
				Me.OnVatSalesChanging(value)
				Me.SendPropertyChanging
				Me._VatSales = value
				Me.SendPropertyChanged("VatSales")
				Me.OnVatSalesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VatExemptSales", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property VatExemptSales() As Decimal
		Get
			Return Me._VatExemptSales
		End Get
		Set
			If ((Me._VatExemptSales = value)  _
						= false) Then
				Me.OnVatExemptSalesChanging(value)
				Me.SendPropertyChanging
				Me._VatExemptSales = value
				Me.SendPropertyChanged("VatExemptSales")
				Me.OnVatExemptSalesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalSales", DbType:="Decimal(18,2)")>  _
	Public Property TotalSales() As System.Nullable(Of Decimal)
		Get
			Return Me._TotalSales
		End Get
		Set
			If (Me._TotalSales.Equals(value) = false) Then
				Me.OnTotalSalesChanging(value)
				Me.SendPropertyChanging
				Me._TotalSales = value
				Me.SendPropertyChanged("TotalSales")
				Me.OnTotalSalesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VatAmount", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property VatAmount() As Decimal
		Get
			Return Me._VatAmount
		End Get
		Set
			If ((Me._VatAmount = value)  _
						= false) Then
				Me.OnVatAmountChanging(value)
				Me.SendPropertyChanging
				Me._VatAmount = value
				Me.SendPropertyChanged("VatAmount")
				Me.OnVatAmountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalAmount", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property TotalAmount() As Decimal
		Get
			Return Me._TotalAmount
		End Get
		Set
			If ((Me._TotalAmount = value)  _
						= false) Then
				Me.OnTotalAmountChanging(value)
				Me.SendPropertyChanging
				Me._TotalAmount = value
				Me.SendPropertyChanged("TotalAmount")
				Me.OnTotalAmountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaymentMethod", DbType:="NVarChar(50)")>  _
	Public Property PaymentMethod() As String
		Get
			Return Me._PaymentMethod
		End Get
		Set
			If (String.Equals(Me._PaymentMethod, value) = false) Then
				Me.OnPaymentMethodChanging(value)
				Me.SendPropertyChanging
				Me._PaymentMethod = value
				Me.SendPropertyChanged("PaymentMethod")
				Me.OnPaymentMethodChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CashReceived", DbType:="Decimal(18,2)")>  _
	Public Property CashReceived() As System.Nullable(Of Decimal)
		Get
			Return Me._CashReceived
		End Get
		Set
			If (Me._CashReceived.Equals(value) = false) Then
				Me.OnCashReceivedChanging(value)
				Me.SendPropertyChanging
				Me._CashReceived = value
				Me.SendPropertyChanged("CashReceived")
				Me.OnCashReceivedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChangeAmount", DbType:="Decimal(18,2)")>  _
	Public Property ChangeAmount() As System.Nullable(Of Decimal)
		Get
			Return Me._ChangeAmount
		End Get
		Set
			If (Me._ChangeAmount.Equals(value) = false) Then
				Me.OnChangeAmountChanging(value)
				Me.SendPropertyChanging
				Me._ChangeAmount = value
				Me.SendPropertyChanged("ChangeAmount")
				Me.OnChangeAmountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedBy", DbType:="NVarChar(100)")>  _
	Public Property CreatedBy() As String
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (String.Equals(Me._CreatedBy, value) = false) Then
				Me.OnCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._CreatedBy = value
				Me.SendPropertyChanged("CreatedBy")
				Me.OnCreatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedAt", DbType:="DateTime NOT NULL")>  _
	Public Property CreatedAt() As Date
		Get
			Return Me._CreatedAt
		End Get
		Set
			If ((Me._CreatedAt = value)  _
						= false) Then
				Me.OnCreatedAtChanging(value)
				Me.SendPropertyChanging
				Me._CreatedAt = value
				Me.SendPropertyChanged("CreatedAt")
				Me.OnCreatedAtChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_POSTransactionDetails")>  _
Partial Public Class tbl_POSTransactionDetail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _DetailID As Integer
	
	Private _TransactionID As Integer
	
	Private _ProductID As String
	
	Private _ProductName As String
	
	Private _Price As Decimal
	
	Private _Quantity As Integer
	
	Private _ExtendPrice As System.Nullable(Of Decimal)
	
	Private _Discount As Decimal
	
	Private _Total As Decimal
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDetailIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnDetailIDChanged()
    End Sub
    Partial Private Sub OnTransactionIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnTransactionIDChanged()
    End Sub
    Partial Private Sub OnProductIDChanging(value As String)
    End Sub
    Partial Private Sub OnProductIDChanged()
    End Sub
    Partial Private Sub OnProductNameChanging(value As String)
    End Sub
    Partial Private Sub OnProductNameChanged()
    End Sub
    Partial Private Sub OnPriceChanging(value As Decimal)
    End Sub
    Partial Private Sub OnPriceChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As Integer)
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    Partial Private Sub OnExtendPriceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnExtendPriceChanged()
    End Sub
    Partial Private Sub OnDiscountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnDiscountChanged()
    End Sub
    Partial Private Sub OnTotalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DetailID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property DetailID() As Integer
		Get
			Return Me._DetailID
		End Get
		Set
			If ((Me._DetailID = value)  _
						= false) Then
				Me.OnDetailIDChanging(value)
				Me.SendPropertyChanging
				Me._DetailID = value
				Me.SendPropertyChanged("DetailID")
				Me.OnDetailIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TransactionID", DbType:="Int NOT NULL")>  _
	Public Property TransactionID() As Integer
		Get
			Return Me._TransactionID
		End Get
		Set
			If ((Me._TransactionID = value)  _
						= false) Then
				Me.OnTransactionIDChanging(value)
				Me.SendPropertyChanging
				Me._TransactionID = value
				Me.SendPropertyChanged("TransactionID")
				Me.OnTransactionIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductID", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ProductID() As String
		Get
			Return Me._ProductID
		End Get
		Set
			If (String.Equals(Me._ProductID, value) = false) Then
				Me.OnProductIDChanging(value)
				Me.SendPropertyChanging
				Me._ProductID = value
				Me.SendPropertyChanged("ProductID")
				Me.OnProductIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductName", DbType:="NVarChar(200) NOT NULL", CanBeNull:=false)>  _
	Public Property ProductName() As String
		Get
			Return Me._ProductName
		End Get
		Set
			If (String.Equals(Me._ProductName, value) = false) Then
				Me.OnProductNameChanging(value)
				Me.SendPropertyChanging
				Me._ProductName = value
				Me.SendPropertyChanged("ProductName")
				Me.OnProductNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Price", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property Price() As Decimal
		Get
			Return Me._Price
		End Get
		Set
			If ((Me._Price = value)  _
						= false) Then
				Me.OnPriceChanging(value)
				Me.SendPropertyChanging
				Me._Price = value
				Me.SendPropertyChanged("Price")
				Me.OnPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="Int NOT NULL")>  _
	Public Property Quantity() As Integer
		Get
			Return Me._Quantity
		End Get
		Set
			If ((Me._Quantity = value)  _
						= false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExtendPrice", DbType:="Decimal(18,2)")>  _
	Public Property ExtendPrice() As System.Nullable(Of Decimal)
		Get
			Return Me._ExtendPrice
		End Get
		Set
			If (Me._ExtendPrice.Equals(value) = false) Then
				Me.OnExtendPriceChanging(value)
				Me.SendPropertyChanging
				Me._ExtendPrice = value
				Me.SendPropertyChanged("ExtendPrice")
				Me.OnExtendPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Discount", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property Discount() As Decimal
		Get
			Return Me._Discount
		End Get
		Set
			If ((Me._Discount = value)  _
						= false) Then
				Me.OnDiscountChanging(value)
				Me.SendPropertyChanging
				Me._Discount = value
				Me.SendPropertyChanged("Discount")
				Me.OnDiscountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property Total() As Decimal
		Get
			Return Me._Total
		End Get
		Set
			If ((Me._Total = value)  _
						= false) Then
				Me.OnTotalChanging(value)
				Me.SendPropertyChanging
				Me._Total = value
				Me.SendPropertyChanged("Total")
				Me.OnTotalChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tbl_Notifications")>  _
Partial Public Class tbl_Notification
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _productID As String
	
	Private _quantity As System.Nullable(Of Integer)
	
	Private _Message As String
	
	Private _CreatedAt As System.Nullable(Of Date)
	
	Private _Seen As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnproductIDChanging(value As String)
    End Sub
    Partial Private Sub OnproductIDChanged()
    End Sub
    Partial Private Sub OnquantityChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnquantityChanged()
    End Sub
    Partial Private Sub OnMessageChanging(value As String)
    End Sub
    Partial Private Sub OnMessageChanged()
    End Sub
    Partial Private Sub OnCreatedAtChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreatedAtChanged()
    End Sub
    Partial Private Sub OnSeenChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnSeenChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_productID", DbType:="NChar(10)")>  _
	Public Property productID() As String
		Get
			Return Me._productID
		End Get
		Set
			If (String.Equals(Me._productID, value) = false) Then
				Me.OnproductIDChanging(value)
				Me.SendPropertyChanging
				Me._productID = value
				Me.SendPropertyChanged("productID")
				Me.OnproductIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_quantity", DbType:="Int")>  _
	Public Property quantity() As System.Nullable(Of Integer)
		Get
			Return Me._quantity
		End Get
		Set
			If (Me._quantity.Equals(value) = false) Then
				Me.OnquantityChanging(value)
				Me.SendPropertyChanging
				Me._quantity = value
				Me.SendPropertyChanged("quantity")
				Me.OnquantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Message", DbType:="NVarChar(255)")>  _
	Public Property Message() As String
		Get
			Return Me._Message
		End Get
		Set
			If (String.Equals(Me._Message, value) = false) Then
				Me.OnMessageChanging(value)
				Me.SendPropertyChanging
				Me._Message = value
				Me.SendPropertyChanged("Message")
				Me.OnMessageChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedAt", DbType:="DateTime")>  _
	Public Property CreatedAt() As System.Nullable(Of Date)
		Get
			Return Me._CreatedAt
		End Get
		Set
			If (Me._CreatedAt.Equals(value) = false) Then
				Me.OnCreatedAtChanging(value)
				Me.SendPropertyChanging
				Me._CreatedAt = value
				Me.SendPropertyChanged("CreatedAt")
				Me.OnCreatedAtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Seen", DbType:="Bit")>  _
	Public Property Seen() As System.Nullable(Of Boolean)
		Get
			Return Me._Seen
		End Get
		Set
			If (Me._Seen.Equals(value) = false) Then
				Me.OnSeenChanging(value)
				Me.SendPropertyChanging
				Me._Seen = value
				Me.SendPropertyChanged("Seen")
				Me.OnSeenChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

Partial Public Class SP_InsertPOSTransactionResult
	
	Private _TransactionID As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TransactionID", DbType:="Int")>  _
	Public Property TransactionID() As System.Nullable(Of Integer)
		Get
			Return Me._TransactionID
		End Get
		Set
			If (Me._TransactionID.Equals(value) = false) Then
				Me._TransactionID = value
			End If
		End Set
	End Property
End Class
